# Generated by Django 5.0.6 on 2024-05-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('summary', models.TextField()),
                ('skills', models.TextField(help_text='Separate your skills with commas')),
                ('experience', models.TextField()),
                ('education', models.TextField()),
            ],
        ),
    ]
